Eng2Hindi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("mainapp.urls",namespace='mainapp')),
]

mainapp/urls.py
from django.urls import path, include
from django.contrib import admin
from .views import home,getdata,about
# from home import views
app_name='mainapp'

urlpatterns = [
    path('',home,name='home'),
    path('about/', about, name='about'),

    path('getdata/<str:input>',getdata,name='getdata'),

]

mainapp/models.py
from django.db import models

# Create your models here.

mainapp/views.py
from django.shortcuts import render,HttpResponse
from django.http import JsonResponse
from .translator import translator
def getdata(request,input):
    result=translator(input)
    print(result)
    return JsonResponse({'data':result})
def home(request):
    return render(request,'mainapp/home.html')



# adding files here from cpy

def about(request):
    return render(request,'mainapp/about.html')

mainapp/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'mainapp/about.css' %}">
{% endblock %}
{% block content %}
<h1>About me </h1>
{% endblock %}

mainapp/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Eng2Hindi</title>
    <link rel="stylesheet" href="{% static 'base.css' %}">
    {% block extra_css %}{% endblock %}
</head>
<body>
<header>
    <h1>Eng2Hindi</h1>
    <nav>
        <div class="home">
            <a href="{% url 'mainapp:home' %}" class="nav-link">Home</a>
        </div>
        <div class="menu">
            <ul>
                <li><a href="#" class="nav-link">About us</a></li>
                <li><a href="#" class="nav-link">Docs</a></li>
            </ul>
        </div>
    </nav>
</header>
{% block content %}
{% endblock %}
</body>
</html>

mainapp/templates/mainapp/home.html
{% extends 'base.html' %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'mainapp/home.css' %}">
{% endblock %}
{% block content %}
<section class="box">
<textarea class="left" id="input" placeholder="text to be translated"></textarea>
<button class="middle" onclick="convert()">convert</button>
<div class="right" id="text"></div>
</section>
<script src="{% static 'mainapp/home.js' %}"></script>
{% endblock %}